### ISSUE TITLE
Can't enter ".." in the input path?

### ISSUE THREAD

**Issue by soichih** [BIDS-Apps/rsHRF#3]
Hello. I am having a problem specifying the input data path for rsHRF command line.

Due to the way we are executing this app, we need to reference our input data through "../" prefix. 
 
```
$ singularity exec -e docker://bids/rshrf:1.0.0 rsHRF --input_file ../5cff8685503da13f7865f2da/5acab41cce736b3a7531808f/bold.nii.gz results --atlas ../5cff86ae503da13f7865f2dc/mask.nii.gz --estimation canon2dd
```

This results in the following error message.

```
WARNING: docker-extract failed, missing executable or libarchive
WARNING: Will use old layer extraction method - this does not handle whiteouts
[33mWARNING: Non existent bind point (directory) in container: '/N/home'
[0m[33mWARNING: Non existent bind point (directory) in container: '/N/u'
[0m[33mWARNING: Non existent bind point (directory) in container: '/N/dc2'
[0m[33mWARNING: Non existent bind point (directory) in container: '/N/soft'
[0m[33mWARNING: Could not chdir to home: /N/u/brlife/Karst
[0mTraceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nibabel/loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/5cff8685503da13f7865f2da/5acab41cce736b3a7531808f/bold.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rsHRF", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/rsHRF/CLI.py", line 243, in main
    run_rsHRF()
  File "/usr/lib/python3.6/site-packages/rsHRF/CLI.py", line 128, in run_rsHRF
    TR = spm_dep.spm.spm_vol(args.input_file).header.get_zooms()[-1]
  File "/usr/lib/python3.6/site-packages/rsHRF/spm_dep/spm.py", line 12, in spm_vol
    v = nib.load(input_nii_file)
  File "/usr/lib/python3.6/site-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: '/5cff8685503da13f7865f2da/5acab41cce736b3a7531808f/bold.nii.gz'
```

It looks like the CLI is stripping the ".." from the path, but I am not sure why it's failing. I have confirmed that the input data exists in the path that I am specifying.

Thank you!

**Comment by madhur-tandon** [comment]
@soichih This is strange I guess. I will look into this later today. Till then, could you try `"../path"` instead of `../path` i.e. enclose the whole path in a string? Let me know what happens!

**Comment by soichih** [comment]
This issue was most likely caused by singularity not mounting required directory due to old kernel version. Closing this now.
