### ISSUE TITLE
Error running rshrf toolbox through docker image bids/rshrf:latest

### ISSUE THREAD

**Issue by NigelCol** [BIDS-Apps/rsHRF#7]
Hi,

I tried running the toolbox through the docker image using the latest version. Following the instructions for the docker version
I used the following commands and encountered the following error.

```
docker pull bids/rshrf
docker run -ti --rm bids/rshrf --GUI
```

Gives the following error : 
```Traceback (most recent call last):
  File "/usr/bin/rsHRF", line 5, in <module>
    from rsHRF.CLI import main
  File "/usr/lib/python3.6/site-packages/rsHRF/__init__.py", line 7, in <module>
    import rsHRF.CLI
  File "/usr/lib/python3.6/site-packages/rsHRF/CLI.py", line 8, in <module>
    from .rsHRF_GUI import run
  File "/usr/lib/python3.6/site-packages/rsHRF/rsHRF_GUI/__init__.py", line 4, in <module>
    from . import gui_windows
  File "/usr/lib/python3.6/site-packages/rsHRF/rsHRF_GUI/gui_windows/__init__.py", line 1, in <module>
    from . import inputWindow
  File "/usr/lib/python3.6/site-packages/rsHRF/rsHRF_GUI/gui_windows/inputWindow.py", line 2, in <module>
    from tkinter       import Toplevel, Checkbutton, IntVar, Button, filedialog, NORMAL, DISABLED, OptionMenu, StringVar, Label
ModuleNotFoundError: No module named 'tkinter'
```

The same is true for : 
```
docker run -ti --rm bids/rsHRF --help
```

Tested using Docker image using the latest version on both a Windows 10 and Linux ubuntu 16.04 system.

I wonder if there's something I'm doing wrong or there's an issue with the latest docker image.

Thanks,

Nigel

**Comment by madhur-tandon** [comment]
@AmoghJohri You would want to look into this since it's related to GUI stuff.

**Comment by AmoghJohri** [comment]
Dear @NigelCol,

Thank you for raising the issue. The following [commit](https://github.com/BIDS-Apps/rsHRF/commit/0ec7dd8b8a5eeba70484355ad2e57faac98e1dcc) solves the same. Hence, I shall be closing it.
